#### 目录介绍
- 01.快速了解异常
    - 1.1 什么是异常
    - 1.2 为何要有异常
    - 1.3 异常思考
- 02.异常体系结构图
    - 2.1 架构图展示
    - 2.2 架构图说明
- 03.异常特点说明
    - 3.1 Exception说明
    - 3.2 Error说明
    - 3.3 异常和错误区别
- 04.Throwable类Api
    - 4.1 异常处理重要信息
    - 4.2 一些方法区别
    - 4.3 异常栈轨迹说明



### 01.快速了解异常
#### 1.1 什么是异常
- 什么是异常
    - 是指正常程序流程所不能处理，或者没有处理的异常情况，或者异常事件等。
    - 举个例子，比如算术运算被0除，数组下标越界，使用的对象为null等。
- 传递错误信息给接收者
    - 发现错误的理想时机是在编译阶段，也就是程序在编码过程中发现错误，然而一些业务逻辑错误，编译器并不能一定会找到错误，余下的问题需要在程序运行期间解决，这就需要发生错误的地方能够准确的将错误信息传递给某个接收者，以便接收者知道如何正确的处理这个错误信息。


#### 1.2 为何要有异常
- 异常的由来
    - C语言以及其它早期语言的错误处理方式通常是一些约定俗成的模式，比如返回某个错误标记或者设置某个特殊的值通过判断值来确认是否发生了错误。然而长期来看这种错误处理方式由于需要大量的判断以及细致的错误检查而使代码逻辑较为复杂，因此不利于构建大型健壮性的系统。
    - 解决的方法是，用强制规定的形式来消除错误处理过程中随心所欲的因素。“异常”这个词有“我对此感到意外”的意思，当错误问题出现了，你可能不知道出现在哪里，或者出现了什么错误，也不知道怎么解决。
    - 那么就停下来，将这个问题提供给更高的环境，看看有没有正确的解决方案。使用异常的另一个好处是，它能够明显的降低代码的复杂程度，避免了大量的错误检查，只需要在一个特定的地方进行异常捕获，并且不需要做任何判断，异常捕获区能够捕获所有发生的错误。
    - 这种异常的处理方式与之前的错误处理方式相比，完全的将“正常做的事儿”与“出现问题怎么办”隔离开来。是代码的读写变得更加井井有条。
- Java异常是一种识别及响应错误的一致性机制
    - Java异常机制可以使程序中异常处理代码和正常业务代码分离，保证程序代码更加优雅，并提高程序健壮性。


#### 1.3 异常思考
- 在有效使用异常的情况下，异常能清晰的回答what，where，why这3个问题：
    - 异常类型，会告诉“什么”被抛出
    - 异常堆栈跟踪，会告诉“在哪“抛出
    - 异常信息，会告诉“为什么“会抛出。
- 看一个异常信息
    - 异常类型，是NullPointerException，空指针异常
    - 异常堆栈跟踪，ZygoteInit.main ---->  RuntimeInit ----> ActivityThread.main ---->  Handler.dispatchMessage ---> View.performClick ---> CrashTestActivity.onClick
    - 异常信息，Attempt to invoke virtual method 'void android.app.Activity.finish()' on a null object reference
    ```
    Process: com.com.yc.ycandroidtool, PID: 16060
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.finish()' on a null object reference
        at com.com.yc.toollib.crash.CrashTestActivity.onClick(CrashTestActivity.java:48)
        at android.view.View.performClick(View.java:7187)
        at android.view.View.performClickInternal(View.java:7164)
        at android.view.View.access$3500(View.java:813)
        at android.view.View$PerformClick.run(View.java:27626)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:230)
        at android.app.ActivityThread.main(ActivityThread.java:7742)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
    ```


### 02.异常体系结构图
#### 2.1 架构图展示
- 理解 Throwable、Exception、Error 的分类
    - ![image](https://upload-images.jianshu.io/upload_images/4432347-246194d0356632f5.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)
    - ![image](https://upload-images.jianshu.io/upload_images/4432347-78a464137c7f1d26.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)




#### 2.2 架构图说明
- 异常的概述
    - 异常就是Java程序在运行过程中出现的错误。
- 异常的分类
    - Exception 和 Error。他们的基类是Throwable
- Error是什么
    - 严重问题，不予处理，因为这种问题一般是很严重，比如: 内存溢出
- Exception是什么
    - 非严重问题，编译时异常：非RuntimeException；运行时异常:  RuntimeException



### 03.异常特点说明
#### 3.1 Exception说明
- Exception有什么特点
    - 1.可以是可被控制(checked) 或不可控制的(unchecked)。
    - 2.表示一个由程序员导致的错误。
    - 3.应该在应用程序级被处理。



#### 3.2 Error说明
- Error有什么特点
    - 1.总是不可控制的(unchecked)。
    - 2.经常用来用于表示系统错误或底层资源的错误。
    - 3.如何可能的话，应该在系统级被捕捉。


#### 3.3 异常和错误区别
- 异常和错误的区别：
    - 异常能被程序本身可以处理，错误是无法处理。



### 04.Throwable类Api
- Throwable类中的常用方法。
    - 注意：catch关键字后面括号中的Exception类型的参数e。
    - Exception就是try代码块传递给catch代码块的变量类型，e就是变量名。
    - catch代码块中语句"e.getMessage();"用于输出错误性质。


#### 4.1 异常处理重要信息
- 通常异常处理常用3个函数来获取异常的有关信息:
    - getCause()：返回抛出异常的原因。如果 cause 不存在或未知，则返回 null。
    - getMessage()：返回异常的消息信息。
    - printStackTrace()：对象的堆栈跟踪输出至错误输出流，作为字段 System.err 的值。
- 其他等Api如下所示
    ```
    String getMessage（） 获取详细信息
    String getLocalizedMessage（）获取用本地语言表示的详细信息
    String toString（）返回对Throwable的简单描述
    void printStackTrace（）打印Throwable的调用栈轨迹 输出到标准错误流
    void printStackTrace（PrintStream）打印Throwable的调用栈轨迹 输出到可选择的流
    void printStackTrace（PrintStream）打印Throwable的调用栈轨迹 输出到可选择的流，调用栈显示了“把你带到异常抛出地点”的方法调用序列。
    Throwable fillInStackTrace（）用于在Throwable对象内部，记录栈帧的当前状态，这在程序重新抛出错误或者异常时很有必要。
    ```


#### 4.2 一些方法区别
- getMessage和getLocalizedMessage有何区别？
    ```
    //返回异常发生时的详细信息
    public string getMessage();
    //返回异常对象的本地化信息。使用Throwable的子类覆盖这个方法，可以声称本地化信息。如果子类没有覆盖该方法，则该方法返回的信息与getMessage（）返回的结果相同
    public string getLocalizedMessage();
    ```
- 有时为了简单会忽略掉catch语句后的代码，这样try-catch语句就成了一种摆设，一旦程序在运行过程中出现了异常，就会忽略处理异常，而错误发生的原因很难查找。


#### 4.3 异常栈轨迹说明
- printStackTrace()方法所提供的信息可以通过getStackTrace()方法来直接访问
    - 这个方法将返回一个由栈轨迹中的元素所构成的数组,其中每一个元素都表示栈中的一桢。元素0是栈顶元素,并且是调用序列中的最后一个方法调用(这个 Throwable被创建和抛出之处)。数组中的最后一个元素和栈底是调用序列中的第一个方法调用。
    ``` java
    public static void print(Throwable throwable) {
        //堆栈跟踪元素，它由 Throwable.getStackTrace() 返回。每个元素表示单独的一个【堆栈帧】。
        //所有的堆栈帧（堆栈顶部的那个堆栈帧除外）都表示一个【方法调用】。堆栈顶部的帧表示【生成堆栈跟踪的执行点】。
        StackTraceElement[] stackTraces = throwable.getStackTrace();
        for (StackTraceElement stackTrace : stackTraces) {
            //获取class的名称，该类包含由该堆栈跟踪元素所表示的执行点
            String clazzName = stackTrace.getClassName();
            //返回源文件名，该文件包含由该堆栈跟踪元素所表示的执行点。
            String fileName = stackTrace.getFileName();
            //返回源行的行号，该行包含由该堆栈该跟踪元素所表示的执行点。
            int lineNumber = stackTrace.getLineNumber();
            //返回方法名，此方法包含由该堆栈跟踪元素所表示的执行点。
            String methodName = stackTrace.getMethodName();
            //如果包含由该堆栈跟踪元素所表示的执行点的方法是一个本机方法，则返回 true。
            boolean nativeMethod = stackTrace.isNativeMethod();
        }
    }
    ```



### 06.异常之Error介绍
#### 6.1 什么是Error(错误)
- Error（错误）:是程序无法处理的错误，表示运行应用程序中较严重问题。
- 大多数错误与代码编写者执行的操作无关，而表示代码运行时 JVM（Java 虚拟机）出现的问题。
- 例如，Java虚拟机运行错误（Virtual MachineError），当 JVM不再有继续执行操作所需的内存资源时，将出现 OutOfMemoryError。这些异常发生时，Java虚拟机（JVM）一般会选择线程终止。




#### 6.2 常见的异常Error
- 抽象方法错误，当应用试图调用抽象方法时抛出：java.lang.AbstractMethodError
断言错误，用来指示一个断言失败的情况：java.lang.AssertionError
- 类循环依赖错误。在初始化一个类时，若检测到类之间循环依赖则抛出该异常：java.lang.ClassCircularityError
- 类格式错误。当Java虚拟机试图从一个文件中读取Java类，而检测到该文件的内容不符合类的有效格式时抛出：java.lang.ClassFormatError
- 错误。是所有错误的基类，用于标识严重的程序运行问题。这些问题通常描述一些不应被应用程序捕获的反常情况：java.lang.Error
- 初始化程序错误。当执行一个类的静态初始化程序的过程中，发生了异常时抛出。静态初始化程序是指直接包含于类中的static语句段：java.lang.ExceptionInInitializerError
- 违法访问错误。当一个应用试图访问、修改某个类的域（Field）或者调用其方法，但是又违反域或方法的可见性声明，则抛出该异常：java.lang.IllegalAccessError
- 不兼容的类变化错误。当正在执行的方法所依赖的类定义发生了不兼容的改变时，抛出该异常。一般在修改了应用中的某些类的声明定义而没有对整个应用重新编译而直接运行的情况下，容易引发该错误：java.lang.IncompatibleClassChangeError
- 实例化错误。当一个应用试图通过Java的new操作符构造一个抽象类或者接口时抛出该异常：java.lang.InstantiationError
内部错误。用于指示Java虚拟机发生了内部错误：java.lang.InternalError
- 链接错误。该错误及其所有子类指示某个类依赖于另外一些类，在该类编译之后，被依赖的类改变了其类定义而没有重新编译所有的类，进而引发错误的情况：java.lang.LinkageError
- 未找到类定义错误。当Java虚拟机或者类装载器试图实例化某个类，而找不到该类的定义时抛出该错误：java.lang.NoClassDefFoundError
- 域不存在错误。当应用试图访问或者修改某类的某个域，而该类的定义中没有该域的定义时抛出该错误：java.lang.NoSuchFieldError
- 方法不存在错误。当应用试图调用某类的某个方法，而该类的定义中没有该方法的定义时抛出该错误：java.lang.NoSuchMethodError
- 内存不足错误。当可用内存不足以让Java虚拟机分配给一个对象时抛出该错误：java.lang.OutOfMemoryError
- 堆栈溢出错误。当一个应用递归调用的层次太深而导致堆栈溢出时抛出该错误：java.lang.StackOverflowError
- 线程结束。当调用Thread类的stop方法时抛出该错误，用于指示线程结束：java.lang.ThreadDeath
- 未知错误。用于指示Java虚拟机发生了未知严重错误的情况：java.lang.UnknownError
- 未满足的链接错误。当Java虚拟机未找到某个类的声明为native方法的本机语言定义时抛出：java.lang.UnsatisfiedLinkError
- 不支持的类版本错误。当Java虚拟机试图从读取某个类文件，但是发现该文件的主、次版本号不被当前Java虚拟机支持的时候，抛出该错误：java.lang.UnsupportedClassVersionError
- 验证错误。当验证器检测到某个类文件中存在内部不兼容或者安全问题时抛出该错误：java.lang.VerifyError
- 虚拟机错误。用于指示虚拟机被破坏或者继续执行操作所需的资源不足的情况：java.lang.VirtualMachineError



#### 6.3 Error发生在哪里
- Error（错误）:是程序无法处理的错误，表示运行应用程序中较严重问题。大多数错误与代码编写者执行的操作无关，而表示代码运行时 JVM（Java 虚拟机）出现的问题。例如，Java虚拟机运行错误（Virtual MachineError），当 JVM 不再有继续执行操作所需的内存资源时，将出现 OutOfMemoryError。这些异常发生时，Java虚拟机（JVM）一般会选择线程终止。这些错误表示故障发生于虚拟机自身、或者发生在虚拟机试图执行应用时，如Java虚拟机运行错误（Virtual MachineError）、类定义错误（NoClassDefFoundError）等。这些错误是不可查的，因为它们在应用程序的控制和处理能力之 外，而且绝大多数是程序运行时不允许出现的状况。对于设计合理的应用程序来说，即使确实发生了错误，本质上也不应该试图去处理它所引起的异常状况。



### 07.异常之Exception
#### 7.1 什么是Exception
- Exception（异常）:是程序本身可以处理的异常。
- Exception 这种异常分两大类运行时异常和非运行时异常(编译异常)。程序中应当尽可能去处理这些异常。


#### 7.2 编译期异常和运行期异常
- Java中的异常被分为两大类：编译时异常和运行时异常。
* 所有的RuntimeException类及其子类的实例被称为运行时异常，其他的异常就是编译时异常
* 编译时异常:    Java程序必须显示处理，否则程序就会发生错误，无法通过编译
* 运行时异常:    无需显示处理，也可以和编译时异常一样处理


#### 7.3 运行时异常
- 都是RuntimeException类及其子类异常，如NullPointerException(空指针异常)、IndexOutOfBoundsException(下标越界异常)等，这些异常是不检查异常，程序中可以选择捕获处理，也可以不处理。这些异常一般是由程序逻辑错误引起的，程序应该从逻辑角度尽可能避免这类异常的发生。运行时异常的特点是Java编译器不会检查它，也就是说，当程序中可能出现这类异常，即使没有用try-catch语句捕获它，也没有用throws子句声明抛出它，也会编译通过。


#### 7.4 非运行时异常：编译异常
- 是RuntimeException以外的异常，类型上都属于Exception类及其子类。从程序语法角度讲是必须进行处理的异常，如果不处理，程序就不能编译通过。如IOException、SQLException等以及用户自定义的Exception异常，一般情况下不自定义检查异常。[博客](https://github.com/yangchong211/YCBlogs)




#### 7.5 被检查的异常
- **定义**: Exception类本身，以及Exception的子类中除了"运行时异常"之外的其它子类都属于被检查异常。
- **特点**: Java编译器会检查它。此类异常，要么通过throws进行声明抛出，要么通过try-catch进行捕获处理，否则不能通过编译。例如，CloneNotSupportedException就属于被检查异常。当通过clone()接口去克隆一个对象，而该对象对应的类没有实现Cloneable接口，就会抛出CloneNotSupportedException异常。
- 是否可以恢复：被检查异常通常都是可以恢复的。




### 7.6 异常Exception有哪些
- 算术条件异常（譬如：整数除零等）：java.lang.ArithmeticException
- 数组索引越界异常。当对数组的索引值为负数或大于等于数组大小时抛出：java.lang.ArrayIndexOutOfBoundsException
- 数组存储异常。当向数组中存放非数组声明类型对象时抛出：java.lang.ArrayStoreException
- 强制类型转换异常。假设有类A和B（A不是B的父类或子类），O是A的实例，那么当强制将O构造为类B的- 实例时抛出该异常。该异常经常被称为强制类型转换异常：java.lang.ClassCastException
- 找不到类异常。当应用试图根据字符串形式的类名构造类，而在遍历CLASSPAH之后找不到对应名称的class文件时，抛出该异常：java.lang.ClassNotFoundException
- 不支持克隆异常。当没有实现Cloneable接口或者不支持克隆方法时,调用其clone()方法则抛出该异常：java.lang.CloneNotSupportedException
- 枚举常量不存在异常。当应用试图通过名称和枚举类型访问一个枚举对象，但该枚举对象并不包含常量时，抛出该异常：java.lang.EnumConstantNotPresentException
- 根异常。用以描述应用程序希望捕获的情况：java.lang.Exception
- 违法的访问异常。当应用试图通过反射方式创建某个类的实例、访问该类属性、调用该类方法，而当时又无法访问类的、属性的、方法的或构造方法的定义时抛出该异常：java.lang.IllegalAccessException
违法的监控状态异常。当某个线程试图等待一个自己并不拥有的对象（O）的监控器或者通知其他线程等待该对象（O）的监控器时，抛出该异常：java.lang.IllegalMonitorStateException
- 违法的状态异常。当在Java环境和应用尚未处于某个方法的合法调用状态，而调用了该方法时，抛出该异常：java.lang.IllegalStateException
- 违法的线程状态异常。当线程尚未处于某个方法的合法调用状态，而调用了该方法时，抛出异常：java.lang.IllegalThreadStateException
- 索引越界异常。当访问某个序列的索引值小于0或大于等于序列大小时，抛出该异常：java.lang.IndexOutOfBoundsException
- 实例化异常。当试图通过newInstance()方法创建某个类的实例，而该类是一个抽象类或接口时，抛出该异常：java.lang.InstantiationException
- 被中止异常。当某个线程处于长时间的等待、休眠或其他暂停状态，而此时其他的线程通过Thread的interrupt方法终止该线程时抛出该异常：java.lang.InterruptedException
- 数组大小为负值异常。当使用负数大小值创建数组时抛出该异常：java.lang.NegativeArraySizeException
- 属性不存在异常。当访问某个类的不存在的属性时抛出该异常：java.lang.NoSuchFieldException
- 方法不存在异常。当访问某个类的不存在的方法时抛出该异常：java.lang.NoSuchMethodException
空指针异常。当应用试图在要求使用对象的地方使用了null时，抛出该异常。譬如：调用null对象的实例方法、访问null对象的属性、计算null对象的长度、使用throw语句抛出null等等：java.lang.NullPointerException
- 数字格式异常。当试图将一个String转换为指定的数字类型，而该字符串确不满足数字类型要求的格式时，抛出该异常：java.lang.NumberFormatException
- 运行时异常。是所有Java虚拟机正常操作期间可以被抛出的异常的父类：java.lang.RuntimeException
安全异常。由安全管理器抛出，用于指示违反安全情况的异常：java.lang.SecurityException
字符串索引越界异常。当使用索引值访问某个字符串中的字符，而该索引值小于0或大于等于序列大小时，抛出该异常：java.lang.StringIndexOutOfBoundsException
- 类型不存在异常。当应用试图以某个类型名称的字符串表达方式访问该类型，但是根据给定的名称又找不到该类型是抛出该异常。该异常与ClassNotFoundException的区别在于该异常是unchecked（不被检查）异常，而ClassNotFoundException是checked（被检查）异常：java.lang.TypeNotPresentException
不支持的方法异常。指明请求的方法不被支持情况的异常：java.lang.UnsupportedOperationException 




### 其他介绍
#### 01.关于博客汇总链接
- 1.[技术博客汇总](https://www.jianshu.com/p/614cb839182c)
- 2.[开源项目汇总](https://blog.csdn.net/m0_37700275/article/details/80863574)
- 3.[生活博客汇总](https://blog.csdn.net/m0_37700275/article/details/79832978)
- 4.[喜马拉雅音频汇总](https://www.jianshu.com/p/f665de16d1eb)
- 5.[其他汇总](https://www.jianshu.com/p/53017c3fc75d)



#### 02.关于我的博客
- github：https://github.com/yangchong211
- 知乎：https://www.zhihu.com/people/yczbj/activities
- 简书：http://www.jianshu.com/u/b7b2c6ed9284
- csdn：http://my.csdn.net/m0_37700275
- 喜马拉雅听书：http://www.ximalaya.com/zhubo/71989305/
- 开源中国：https://my.oschina.net/zbj1618/blog
- 泡在网上的日子：http://www.jcodecraeer.com/member/content_list.php?channelid=1
- 邮箱：yangchong211@163.com
- 阿里云博客：https://yq.aliyun.com/users/article?spm=5176.100- 239.headeruserinfo.3.dT4bcV
- segmentfault头条：https://segmentfault.com/u/xiangjianyu/articles
- 掘金：https://juejin.im/user/5939433efe88c2006afa0c6e





