#### 目录介绍
- 01.异常处理形式
- 02.抛出异常
- 03.捕获异常
- 04.Finally讲解
- 05.捕获链原理
- 06.如何全局捕获








### 01.异常处理形式
- dart 使用经典的try-catch处理异常，使用关键字throw抛出一个异常。





### 02.抛出异常
- 看看如何抛出异常
    ```
      void test1(){
        divide(10, 0);
      }
    
      divide(int a, int b) {
        if (b == 0) {
          throw new IntegerDivisionByZeroException();
        }
        return a / b;
      }
    ```
    - 当b变量的值为0的时候，抛出一个内置的异常IntegerDivisionByZeroException。
- 如何定义异常日志呢？
    - 可以在异常中携带一个字符串信息。
    ```
      void test1(){
        divide(10, 0);
      }
    
      divide(int a, int b) {
        if (b == 0) {
          throw new Exception('逗比，不能为0的');
        }
        return a / b;
      }
    ```


### 03.捕获异常
- 某种类型的异常可以通过on关键字捕获，如下：
    ```
      void test1(){
        try {
          divide(10, 0);
        } on IntegerDivisionByZeroException {
          print('逗比，异常被捕获了');
        }
      }
    
      divide(int a, int b) {
        if (b == 0) {
          throw new IntegerDivisionByZeroException();
        }
        return a / b;
      }
    ```
- 注意问题，捕获的异常层级要大于抛出的异常，否则捕获会失败
    - 还是会抛出异常'逗比，不能为0的'，因为Exception比IntegerDivisionByZeroException层级要高。
    ```
      void test1(){
        try {
          divide(10, 0);
        } on IntegerDivisionByZeroException {
          print('逗比，异常被捕获了');
        }
      }
    
      divide(int a, int b) {
        if (b == 0) {
          throw new Exception('逗比，不能为0的');
        }
        return a / b;
      }
    ```
- 如果你不知道抛出异常的类型，或者不确定，可以使用catch块处理任意类型的异常。
    ```
      void test1(){
        try {
          divide(10, 0);
        } on IntegerDivisionByZeroException {
          print('逗比，异常被捕获了');
        } catch (e) {
          print(e);
        }
      }
    
      divide(int a, int b) {
        if (b == 0) {
          throw new Exception('yc other exception.');
        }
        return a / b;
      }
    ```




### 04.Finally讲解
- dart也提供了finally块，即是否发生异常这个块都会执行。
    ```
      void test1(){
        try {
          divide(10, 0);
        } on IntegerDivisionByZeroException {
          print('逗比，异常被捕获了');
        } catch (e) {
          print(e);
        }finally {
          print('I will always be executed!');
        }
      }
    
      divide(int a, int b) {
        if (b == 0) {
          throw new Exception('yc other exception.');
        }
        return a / b;
      }
    ```













